### ISSUE TITLE
open() discrepancy with java-processing API

### ISSUE THREAD

**Issue by aparrish** [jdf/Processing.py-Bugs#104]
`open()` has [a meaning in Java Mode](http://processing.org/reference/open_.html) very different from its meaning in processing.py. I haven't seen a note of this anywhere? Should the functionality of Java-Mode `open()` be preserved somewhere somehow?

**Comment by jdf** [comment]
It appears that `open()` is no more.

**Comment by benfry** [comment]
Yes, it was removed in 3.x because of this issue w/ Python.

**Comment by jdf** [comment]
Available as Python Mode 3014.
