### ISSUE TITLE
Weird issue with commented code lines still being run

### ISSUE THREAD

**Issue by oneilsh** [jdf/Processing.py-Bugs#123]
I'm not exactly sure what to call this bug, but I was able to reproduce it like so:

Install processing and python mode
From the examples, open the "Flocking" example
Save example as new sketch for editing.
Run example
Comment out "self.flock(boids)" in boid.py, save
Run again, *notice that the boids are still flocking
Make trivial change to boid constructor (0 to 0.0), save
Run again, notice that boids are no longer flocking*
un-comment-out "self.flock(boids)" in boid.py, save
Run again, notice that flocking has resumed.

When commenting out the flocking computations, I was expecting that they would stop flocking, but making a trivial change to the constructor and resaving seemed to make the difference. (I found this one as I was trying to determine if the boids example was slow compared to Java mode for rendering reasons or O(n^2) reasons :-P)

**Comment by jdf** [comment]
Thank you. I can reproduce it by simply re-dirtying and re-saving the same file, i.e., the first time I comment it out and save it, the sketch does not see the change. The, if I add a space and delete the space and re-save it, then it sees the change. Very vexing.

**Comment by vecst** [comment]
Seems if you open the *.py file in a seperate editor and save from the editor it notices the comment out. I guess processing isn't writing to the file?

**Comment by jdf** [comment]
Fixed in build 3010. Sorry for the long delay!

**Comment by oneilsh** [comment]
Awesome! You're my hero--I'm teaching a class in programming using processing.py and it's an amazing addition to the processing landscape. Hopefully build 3010 makes out to the IDE updater soon :)

**Comment by jdf** [comment]
@oneilsh 3011 is out now. The mode manager is buggy, and has no idea what the current build is. Just update to whatever it thinks is the latest build, and you'll see 3011 (or greater) come down.

Please contact me at jdf@pobox.com and tell me about your programming class!
