### ISSUE TITLE
Unable to open serial library

### ISSUE THREAD

**Issue by dschmenk** [jdf/Processing.py-Bugs#124]
When trying to open the serial library:
```
portName = Serial.list()[len(Serial.list()) - 1] # Pick last serial port in list
myPort = Serial(this, portName, 57600)
```
I get the error:
```
processing.app.SketchException: java.lang.UnsatisfiedLinkError: jssc.SerialNativeInterface.openPort(Ljava/lang/String;Z)J
    at jssc.SerialNativeInterface.openPort(Native Method)
    at jssc.SerialPort.openPort(SerialPort.java:158)
        ...
```
It appears that the native serial port interface library isn't being loaded. Java mode Processing examples that open the serial port work fine.

**Comment by kazimuth** [comment]
Art you importing it with `add_library`?

**Comment by dschmenk** [comment]
Yes. It appears to be picking up serial.jar but not jssc.jar.

**Comment by jdf** [comment]
Please give detailed steps to reproduce, including operating system, Processing version, etc.

**Comment by dschmenk** [comment]
OSX 10.10.2
Processing 2.2.1

Enter this code:
'''
add_library('serial')

def setup():
    portName = Serial.list()[len(Serial.list()) - 1] # Pick last serial port in list
    portArduino = Serial(this, portName, 57600)

'''

Run sketch.

**Comment by dschmenk** [comment]
I was successfully able to open the serial ports on 32 bit Linux and 32 bit Windows XP. Still no-go on OSX Yosemite.

**Comment by jdf** [comment]
Fixed in https://github.com/jdf/processing.py/releases/tag/0406
