### ISSUE TITLE
global name 'key' not defined before keypress

### ISSUE THREAD

**Issue by aparrish** [jdf/Processing.py-Bugs#128]
This is a quibbly difference in semantics between Java Processing and Processing.py. Compare the behavior of these two sketches. First, in Java Processing:

```
void draw() {
  background(0);
  text(key, 50, 50);
}
```

...and then, in Processing.py:

```
def draw():
  background(0)
  text(key, 60, 80)
```

The Processing.py version doesn't make it past the first call to `draw`, exiting with a NameError ("global name 'key' is not defined"). The Java version runs fine, though it displays a missing character glyph until a key is pressed. (This might not make a practical difference to anyone in a real-world scenario, but I thought I'd at least note it here in case someone else comes across the same problem.)

**Comment by jdf** [comment]
No, not quibbly at all. Thanks.

**Comment by jdf** [comment]
Fixed in 0408.

**Comment by aparrish** [comment]
awesome, thank you!
