### ISSUE TITLE
A little bug in Tutorials

### ISSUE THREAD

**Issue by justalittlenoob** [jdf/Processing.py-Bugs#129]
I think there is a little bug in Tutorials http://py.processing.org/tutorials/objects/  in the demo:
```python
c = color(0)
x = 0.0
y = 100.0
speed = 1.0
def setup():
  size(200, 200)
def draw():
  background(255)
  move()
  display()
def move():
  x = x + speed                             <<--------------global x
                                                            x = x + speed
  if x > width:                                                      
          x = 0
def display():
  fill(c)
  rect(x, y, 30, 10)
```

in the function move(), the x should be global，Otherwise，there would be an error

**Comment by ruyimarone** [comment]
I believe the same issue happens in the example code for the [draw] (http://py.processing.org/reference/draw.html) function.

**Comment by tildebyte** [comment]
Not all of the examples have been updated for the change to `global` behavior (including those in the docs).

**Comment by Prabhnith** [comment]
this was solved "little bug in Tutorials http://py.processing.org/tutorials/objects/" ref #87
please close this issue.
