### ISSUE TITLE
Processing.py Reference: Multiline comments typos

### ISSUE THREAD

**Issue by calwas** [jdf/Processing.py-Bugs#131]
The Multiline Comments page at http://py.processing.org/reference/multilinecomment.html has two typos:

* The **Syntax** section shows Java comment syntax.
* The **Related** section contains a link to itself.

**Comment by Prabhnith** [comment]
this issue doesn't exists anymore. Kindly close the issue @jdf

**Comment by calwas** [comment]
Verified this issue no longer exists. Closing.
