### ISSUE TITLE
Several of the examples fail with UnboundLocalError

### ISSUE THREAD

**Issue by zencuke** [jdf/Processing.py-Bugs#140]
I just downloaded a current version of processing and then installed python. Next I walked through all of the example programs and demos. There were quite a few failures including a couple of crashes. The most common error (tickle was the most recent I tried) failed with the following error. Adding a global statement to the relevant functions fixed the problem. My recollection is that all of the examples in the "Interaction" folder had the same problem plus a few others. When I get a chance I'll try to duplicate the crashes and file them as separate bugs.

processing.app.SketchException: UnboundLocalError: local variable 'x' referenced before assignment
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:247)
	at jycessing.mode.run.SketchRunner.access$4(SketchRunner.java:226)
	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:121)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jdf** [comment]
Thanks, @zencuke. Please don't trouble yourself with separate bugs for all of those; I'll fix the Interaction folder examples en masse.

**Comment by zencuke** [comment]
Sure. I was only going to file the hard crashes as separate bugs. The hard crashes weren't in the Interaction folder. I figure all of the errors which showed as trapped exceptions were similar and easy to find. On the other hand my test was simple. See if the example runs without being edited first. I guess anyone can do that, even for the crashes, once they are aware of the failures.

It is not important but I was curious why these errors appeared. Did the python version change in  processing.py or something?

**Comment by zencuke** [comment]
OK

**Comment by jdf** [comment]
There was a brief window in time where all variables were magically treated as globals, but that experiment was abandoned.

Please do reopen if and when you find other wrong examples.
