### ISSUE TITLE
printArray(PFont.list()) on typography examples not working

### ISSUE THREAD

**Issue by villares** [jdf/Processing.py-Bugs#142]
Warning! Newbie questions on this issue:
Shouldn't `printArray(PFont.list())` print a list of available fonts on the console?
I can't find it on the Python Mode function reference, should it be removed from the examples?
Am I missing something? Is there a more Pythonic way of printing the list we could put on the examples?

**Comment by jdf** [comment]
```python
print "\n".join(PFont.list())
```
works for me.

**Comment by villares** [comment]
So we'll put that at the example code, instead of 'printArray'?

**Comment by jdf** [comment]
Sure, or

```python
for font in PFont.list():
    print font
```

which may be easier for new programmers to understand.
