### ISSUE TITLE
translate() & rotate() composition problem

### ISSUE THREAD

**Issue by villares** [jdf/Processing.py-Bugs#143]
I'm translating (no pun intended) this tutorial to Python Mode: https://processing.org/tutorials/transform2d/

But something is going wrong, see the last image for the actual result of the code.
![screen shot 2015-12-17 at 11 38 54 am](https://cloud.githubusercontent.com/assets/3694604/11870989/6df67596-a4b3-11e5-9f83-04d1c001e793.png)
![screen shot 2015-12-17 at 11 39 04 am](https://cloud.githubusercontent.com/assets/3694604/11870987/6dcd053a-a4b3-11e5-9b8f-05161c8f904c.png)
![screen shot 2015-12-17 at 11 39 35 am](https://cloud.githubusercontent.com/assets/3694604/11870988/6dcfeafc-a4b3-11e5-93a7-d6491078795d.png)

**Comment by jdf** [comment]
The rotated rectangle should be drawn at 0, 0; not 40, 40. You've already translated 40, 40.

**Comment by villares** [comment]
Thank you!
