### ISSUE TITLE
Using Processing.py with PyCharm?

### ISSUE THREAD

**Issue by CaravaggiosFillide** [jdf/Processing.py-Bugs#145]
Is there any way of using PyCharm as the IDE for Processing.py?

**Comment by tildebyte** [comment]
Define what you would like from an "IDE".
I use Sublime Text, and now Atom to some degree; they provide syntax highlighting, snippets (e.g. type `def{TAB}` and get function boilerplate), and some other features, including running sketches with a keystroke, and trapping errors into an editor frame and jumping to the file and line with the error.
It's not so good with "intellisense", but because what we're really doing is scripting a Java runtime with Python, I don't think it's possible to have the level of introspection needed to get that.

**Comment by CaravaggiosFillide** [comment]
I have tried a variety of editors over the past years. In the beginning notepad++ a lot then I took the bull by it's horns and got down with vim but lately I have found PyCharm with vim key-bindings as the most efficient for me when it comes to Python, therefor the question. I have also tried Atom which I also quite like. Could you just brief me in general terms what I would need to do to run sketches from other editors? Do I direct the interpreter to the processing jython interpreter or do I write a macro that runs a shell command prompting processing-java to run it via a terminal? I can't seem to run python sketches from processing-java as it looks for a .pde and not a .pyde otherwise I think I could figure it out. 

And yes I look for basically the same things as you mention, but I understand that the level of syntax highlighting or code-completion in this environment might limit the scope from accessing processing native clues, but that's fine.

**Comment by tildebyte** [comment]
I haven't tried running sketches directly from Atom, but it works very smoothly from Sublime Text. All you need to do is point ST at the cmd file which comes with Processing.py, along with telling ST where in the build command to put e.g. the working dir and filename. I would imagine that Atom would be similar.

**Comment by tildebyte** [comment]
There's [build](https://atom.io/packages/build), which seems very similar to Sublime Text's way of doing things, and is the most popular package of it's type. As I said, I haven't touched it, but it looks straightforward.

**Comment by tildebyte** [comment]
https://atom.io/packages/build-processing

**Comment by CaravaggiosFillide** [comment]
Thanks for your support. I got everything working with Atom, should have searched their extension repository before troubling with a question here but perhaps somebody else will have use for the answer when they come here looking.

**Comment by tildebyte** [comment]
np, hth

**Comment by lucaslopesf** [comment]
I was able to write Java code in Atom and run using this [package](https://atom.io/packages/processing). But I can't with PyProcessing, could you help me? @tildebyte

**Comment by tildebyte** [comment]
Just to verify:
1) You have "atom-build" installed
2) "processing-py" commandline tool is installed
3) "processing-py" commandline tool is in your PATH.
If all of that is true, I would say to make sure that nothing has changed with atom-build in the last year or so. I haven't touched this in a while, and I don't have time to look at it right now.
Also, any error messages or logs you might have would be a great help.

**Comment by JamesWClark** [comment]
I have verified all three steps and I get `No eligible build target` error message. What's the configuration step to get Atom to run the sketch?

![Imgur](https://i.imgur.com/qq2UPtO.jpg)
