### ISSUE TITLE
No key trigger for the Yes/No when dialog box appears

### ISSUE THREAD

**Issue by Prabhnith** [jdf/Processing.py-Bugs#147]
![no key trigger for close dialog box](https://cloud.githubusercontent.com/assets/11560449/13118721/9024dec0-d5cb-11e5-98e1-49eae69cb303.png)

**Comment by jdf** [comment]
Is this different from Java mode?

**Comment by Prabhnith** [comment]
no both are having the same problem but for dialog box and under the file menu it works fine

**Comment by jdf** [comment]
Then this is a processing bug, not Python Mode.
