### ISSUE TITLE
can't import from __future__

### ISSUE THREAD

**Issue by gcbgit** [jdf/Processing.py-Bugs#148]
I get an `from __future__ imports must occur at the beginning of the file` error even when the import line is the first line of the sketch.

trying to do:
```python
from __future__ import division
```

**Comment by jdf** [comment]
When I run this program:

```python
from __future__ import division

def setup():
    pass

def draw():
    pass
```

it works fine for me. Please paste into this bug a minimal complete example that demonstrates the bug. Thanks!

**Comment by Prabhnith** [comment]
@gcbgit  you have written "future" instead of "__future__" .

**Comment by gcbgit** [comment]
This fails for me:

```
from __future__ import division

def setup():
    size(800,800)
    
def draw(): pass

```

**Comment by GoToLoop** [comment]
import __future__
division = __future__.division

def setup():
    size(800, 600)
    noLoop()
    print division

def draw():
    pass

**Comment by jdf** [comment]
Pushed to build 3009.
