### ISSUE TITLE
unpacking *args doesn't work inside stroke()

### ISSUE THREAD

**Issue by gcbgit** [jdf/Processing.py-Bugs#149]
color=[200,200,200]
stroke(*color)

fails with a variety of errors.  I suspect the arguments aren't being unpacked before being passed along to the Processing layer.

**Comment by jdf** [comment]
When I run the program

```python
x = [200, 0, 100]
stroke(*x)
ellipse(width/2, height/2, width/2.25, height/2.25)
```

It works as expected for me.

It could  be because ```color``` is a processing reserved word?
