### ISSUE TITLE
specifying size() using a formula

### ISSUE THREAD

**Issue by piotrlukasik** [jdf/Processing.py-Bugs#151]
Hi, in Processing.py 2 I would typically start a project from loading a data table, and based on its contents - number of rows and columns, etc. - calculate the desired size of the display window. This doesn't seem to work in Processing.py 3 (see example below). I hope that this can be fixed! Thanks, Piotr

DisplayWidth = 200
DisplayHeight = 300
size(200, 300)
### --> Run --> Works! Display window size is as desired.

DisplayWidth = 200
DisplayHeight = 300     ### I'd normally use a more sophisticated formula!
size(DisplayWidth, DisplayHeight)

**Comment by jdf** [comment]
"""
As of Processing 3.0, to use variables as the parameters to size() function, place the size() function within the settings() function. There is more information about this on the settings() reference page.
"""

**Comment by piotrlukasik** [comment]
Thank you for this. I have spent over an hour trying to implement this, but
could not figure out how to use variables as the parameters to size() in
the Processing 3.02-Python mode based on java-specific reference page for
settings(), size() and other functions. I would be really grateful for
help. Some of the commands that I tried are below.

Thanks again,

Piotr


###########
Data_Table = loadTable("/Users/Piotr/Dropbox/Documents/test.csv")
print("Loaded Data Table, of %d rows" % Data_Table.getRowCount())
    ### prints("Loaded Data Table, of 3 rows"). Cool.


def setup():
    size(100*Data_Table.getRowCount(), 400)
    ### display size is as requested - but I am apparently in 'active
mode', where lines etc. cannot be drawn outside of functions...

#----- or ------

settings(size(100*Data_Table.getRowCount(), 400))
    ### error: "name 'settings' is not defined"

#----- or -------

settings()
    size(100*Data_Table.getRowCount(), 400)
    ### error: "mismatched input '' expecting EOF"

#----- or -------

def settings():
    size(100*Data_Table.getRowCount(), 400)
    ### no error message but this doesn't work - size defaults to 100x100

**Comment by jdf** [comment]
In the settings function, load your data data table, then call size().
