### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by CaravaggiosFillide** [jdf/Processing.py-Bugs#153]
I have just rewritten one of my main projects in processing to python and it has been a true pleasure. The problem is now that I have both finished the performance I get out of the python version is only a fraction of the java version. (fps java: 60, fps python: 8) even with GPU acceleration on the java binary. 
Is there any way to fix this or is using the python mode inherently this much slower?

**Comment by GoToLoop** [comment]
I've just done 2 Java to Python mode conversions: "Rotating Arcs" & "Wiggling Cube":
https://forum.Processing.org/two/discussion/14071/converting-java-code-to-python-for-dataviz

While Python's "Rotating Arcs" almost lost half performance compared to Java's, I've haven't noticed any from "Wiggling Cube". :bowtie:

**Comment by CaravaggiosFillide** [comment]
The particles example file gives me 60 fps in java and 15 fps in python

**Comment by GoToLoop** [comment]
Where can I find that example? And you also need to post your rewriting.

**Comment by CaravaggiosFillide** [comment]
It's under demos/graphics/examples. Don't think posting my code will do any good in this case since this example relates quite accurately to the problem I am having. Maybe you can check and see if you get the same results?

**Comment by GoToLoop** [comment]
Found the example. But it's already converted to Python Mode. Why the re-written then?

**Comment by CaravaggiosFillide** [comment]
I use it as an example that exists in both java and python to illustrate the performance loss. My code is obviously not in the example directory ;)

**Comment by GoToLoop** [comment]
Ah! Forgot it's another Java Mode sketch you have converted! :dizzy_face:

**Comment by CaravaggiosFillide** [comment]
yes, and considering the code quality of the python code compared to my java code I was naively expecting better performance but that was clearly a misconception. If anybody has any tips on how python mode performance can be improved please let me know. Thanks in advance

**Comment by jdf** [comment]
Python mode, which interprets python in java, is inherently slower than java processing, especially when performing loops. The gpu is not used for executing your program, nor  are multiple processors.

**Comment by GoToLoop** [comment]
I have "You’re receiving notifications because you commented." But strangely I can't see any of those comments?

**Comment by jdf** [comment]
Also, some time ago I created a tutorial about "going native" for performance.

https://github.com/jdf/processing.py/wiki/How-to-call-%22native%22-Java-code-from-your-Python-Mode-sketch
