### ISSUE TITLE
3.0.2 OS X doesn't run Python mode, but 3.0.1 does

### ISSUE THREAD

**Issue by Spaxe** [jdf/Processing.py-Bugs#154]
Hi @jdf,

I'm not sure how to best report this bug—if it's a bug at all, or just my system—because I can't seem to run Processing 3.0.2 on my OS X 10.11 in Python mode.

Clean install, I've deleted everything in `~/Library/Processing` and left everything default. Can't run any of the examples.

I downloaded 3.0.1 and redownloaded Python mode again, works just fine.

Can anyone on a Mac confirm if this is just me?

**Comment by jdf** [comment]
It works fine for me. You don't say in your bug report exactly what you mean by "doesn't run". What actually happens?

**Comment by Spaxe** [comment]
OK, so it's just me. Dang. I don't even know how to reproduce this.

By "doesn't run", I mean I can click on the run button, it turns green, but it never reaches the Jython interpreter, just hanging there. No compiler errors or anything like that, since the code is never run.

**Comment by jdf** [comment]
I wonder if communication between the processing development environment and the python mode sketch runner process is prevented by some firewall process on your computer. Do you have some sort of network filtering in place?

**Comment by Spaxe** [comment]
Turning off firewalls or removing proxies doesn't seem to change anything.

I got another MBP, also 10.11 and it runs 3.0.2 Python mode. It appears to be something rather weird with a specific machine.

Will investigate more tomorrow but this bug is probably just me.

**Comment by jdf** [comment]
If you do figure it out, please let me know.

**Comment by Spaxe** [comment]
I shall try - it's not too important, 3.0.1 works fine.

 - Is there a way to view debug logs?
 - Since you mentioned networking, does it depend on a certain protocol / port?

**Comment by jdf** [comment]
Yes. The sketch runner communicates with the Python editor at `127.0.0.1:8220`.

**Comment by jdf** [comment]
Oh, that's a good question about debug logs. I'm not sure what happens with Processing's stderr.

**Comment by eruditorum-zz** [comment]
I'm having the same issue. I just download 3.0.1, but that hasn't resolved it. I don't believe I have any network filtering in place. Has anybody had any luck resolving this? Thanks in advance!

**Comment by humm** [comment]
Having the same issue with 3.1.1. The play button turns green, nothing happens, and after a while processing becomes unresponsive. I figured a way around it (for me): add `P2D` or `P3D` as renderer to the `size()` function. So, this tutorial code does not run:

```python
def setup():
    size(480, 120)

def draw():
    if  mousePressed:
        fill(0)
    else:
        fill(255)
    ellipse(mouseX, mouseY, 80, 80)
```

But this one does:

```python
def setup():
    size(480, 120, P2D)

def draw():
    if  mousePressed:
        fill(0)
    else:
        fill(255)
    ellipse(mouseX, mouseY, 80, 80)
```

Might only be my configuration (OS X 10.11.5), but it's definitely worth checking out.

**Comment by Spaxe** [comment]
I believe this is fixed in recent versions
