### ISSUE TITLE
PImage not displaying png or jpg

### ISSUE THREAD

**Issue by hs2elec** [jdf/Processing.py-Bugs#155]
This is the code, sorry if the mistake is mine thanks.  
```python
red_car = PImage()
frog = PImage()

def setup():
    size(800, 600 )
    red_car = loadImage("redcar.png")
    frog = loadImage("green_tree_frog.jpg")
    
def draw():
      
    background(0)
    image(frog, 0, 0)   
    image(red_car, 100, 100)  
```

**Comment by jdf** [comment]
I your setup() function, you have to tell python that you're assigning to the global vales `red_car` and `frog` by using the `global` keyword.

Also, those first two lines aren't doing anything.

```python
def setup():
    size(800, 600 )
    global red_car, frog
    red_car = loadImage("redcar.png")
    frog = loadImage("green_tree_frog.jpg")

def draw():
    background(0)
    image(frog, 0, 0)   
    image(red_car, 100, 100) 
```

**Comment by hs2elec** [comment]
thanks for your help and sorry to waste your time.  SH

**Comment by jdf** [comment]
You didn't waste my time. :)

Indeed, I'm thinking about writing a few paragraphs on how crappy `global` is.
