### ISSUE TITLE
dispose() not called on exit

### ISSUE THREAD

**Issue by jsundram** [jdf/Processing.py-Bugs#156]
In java processing sketches, `dispose()` (usually) gets called when exiting a sketch (see [this gist](https://gist.github.com/jsundram/29d5449069d40e59b595)). However, this doesn't happen for processing.py sketches, e.g. in the following minimal sketch I haven't been able to get `dispose()` or `stop()` to be called.

```
def setup():
    return

def draw():
    return

def dispose():
    print("got dispose")

def stop():
    print("got stop")
```

**Comment by jsundram** [comment]
Looks like just you need to wire up `dispose` in [PAppletJythonDriver.java:517](https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/PAppletJythonDriver.java#L517), similarly to `stop()`, which it seems like Processing no longer calls...

**Comment by jdf** [comment]
`dispose()` is not part of the Processing API, and only ever used to get called because a Processing sketch used to happen to be, ultimately, an AWT Applet. It's not an Applet anymore, and I'm not sure what the right thing is to do. I suppose I could create a Python Mode-specific exit callback...

**Comment by jsundram** [comment]
`dispose()` is still getting called in (Java) Processing 3.02.

But yeah, It seems like making sure `stop()` actually gets called from all code paths in both Processing and Processing.py is the way to go, and adding that to the API reference is the way to go . . .

The reason I'm looking for this is to make sure cleanup code gets run consistently when the sketch exits.

**Comment by jdf** [comment]
I sadly have no influence on what happens in Processing proper, but if `dispose()` is indeed still being called in Java mode, then I'll make it so in Python Mode.

**Comment by jdf** [comment]
Fixed in https://github.com/jdf/processing.py/commit/e9123ffc2605994258ba9f1e916855d6aa34694f, will push a new build soon.

**Comment by jdf** [comment]
Pushed in 3006.
