### ISSUE TITLE
Support the serial library

### ISSUE THREAD

**Issue by jdf** [jdf/Processing.py-Bugs#157]
The serial library appears to use method name introspection for callbacks. Consider adding the required callbacks to PAppletJythonDriver.

**Comment by jdf** [comment]
Pushed in 3008.

**Comment by michelezaccagnini** [comment]
I am having troubles receiving messages with the oscP5 library. from the Java example, I got this setup in python


```
from oscP5 import *
from netP5 import * 

def setup():
    size(400, 400)
    background(0)
    port1 = 12000
    oscP5 = OscP5(this, port1)
    loc = NetAddress('127.0.0.1', 12000)
 
 
def draw():pass 
 
 
 
def oscEvent(OscMessage):
   msg = OscMessage
   print "### received an osc message."
   print  " addrpattern: %s " % msg.addrPattern()
   print  " typetag:%s " % msg.typetag()

```
While sending messages works fine, for some reason this doesn't. I think there is something wrong with the way I assign the value in the oscEvent function. 

Can you help me to get the same treatment done for serialEvent() to oscEvent() callback?
