### ISSUE TITLE
Indenting issues.

### ISSUE THREAD

**Issue by schuelaw** [jdf/Processing.py-Bugs#159]
If I have a block of code that is indented and I want to make a new line of code after it that has less indenting, e.g.

```
        for b in Balls:
            b.render()
            b.update()
            if b.isDead():
                Balls.remove(b)
```

I put my cursor at the end of the line `Balls.remove(b)` and hit enter, the cursor will open a new line and match the indent of the `Balls.remove(b)`.  Hitting backspace will back up one indent level + 1 space, the extra 1 space is a bug (I think).  If I hit backspace again, it will jump back two _additional_ levels of indentation (instead of just one), and still have the 1 extra space, if I backspace in an attempt to get back to the leftmost edge of the editing window, when I get within one indent of the left side, the next backspace will put me at the end of the previous line (I suspect that it's trying to back up one more indent, but the 1 space is causing it to go to the previous line).  

The only way to get it back to the leftmost edge is to hit the left arrow key 3 times.  This behavior is pretty trying.  I don't know how that extra space character is getting introduced, but I believe it is the cause of the problems.

(Edit: this bug is in the most recent version 4/22/2016)
(Edit: This bug is in the linux 3.0.2 64bit version.  It is not present in the Windows 3.0.2 64bit version.)

**Comment by jdf** [comment]
Yep, reproduced; thank you! Workaround until I fix it: use shift-tab to dedent instead of backspace.

**Comment by jdf** [comment]
It also happens on OS X. You're quite confident it doesn't happen on Windows? That would mean a bug in the Java runtime on one or more platforms.

**Comment by schuelaw** [comment]
Sorry, to say "not present" in Windows was an overstatement.  The extra space issue doesn't seem to be present, but the multiple de-indents on a single backspace does seem to be an issue.  Also, I can't swear that the extra space issue doesn't occur in Windows, I don't have easy access to a windows machine and only did a quick opportunistic test yesterday on a student's laptop.

**Comment by jdf** [comment]
Pushed in build 3015.
