### ISSUE TITLE
createFont fails when called in global context

### ISSUE THREAD

**Issue by gratefulfrog** [jdf/Processing.py-Bugs#160]
I have found the createFont fails With a: `processing.app.SketchException: java.lang.NullPointerException` in the following context:
```
class Fail:
    def __init__(self):
        self.f = createFont('Courier', 20)
fail = Fail()
def setup():
    None
```
But the code works if organized like this:
```
class Works:
    def __init__(self):
        self.f = createFont('Courier', 20)
works = None
def setup():
    global works
    works = Works()
```
I hope this can be fixed.

Cheers,
Bob

**Comment by gratefulfrog** [comment]
forgotten global statement added, but with no consequence on bug

**Comment by jdf** [comment]
This is a case of an attempt to create a "mixed mode" sketch, but which I can't detect statically. If you have `setup()`, or `draw()`, or any other active-mode infrastructure, then you can't call any of a couple of dozen functions (including `createFont()`) except from one of those Processing active-mode functions. It's a shame, and it's due entirely to the existence of the JavaFX renderer, which is a wart.

**Comment by gratefulfrog** [comment]
I understand, but perhaps the documentation for createFont and the other
such functions should indicate this quirk?

Cheers,
Bob
