### ISSUE TITLE
Lambda expression generates error

### ISSUE THREAD

**Issue by gratefulfrog** [jdf/Processing.py-Bugs#162]
I have come across this strange bug:
```
def setup():
    f = lambda x: print(x)
    f(12)
```
results in this error referring to the line with the `lambda`
`processing.app.SketchException: Maybe there's an unclosed paren or quote mark somewhere before this line?`

But this work-around  runs ok:
```
def setup():
    f = lambda x: p(x)
    f(12)

def p(x):
    print(x)
```
Both work in python3.

As you can see, I'm working in processing.py all day every day!
Ciao,
Bob

**Comment by jdf** [comment]
Python Mode is Python 2.7, not Python 3.

**Comment by gratefulfrog** [comment]
oh, sorry...

On Fri, May 13, 2016 at 3:45 PM, Jonathan Feinberg <notifications@github.com
