### ISSUE TITLE
import serial (pyserial)

### ISSUE THREAD

**Issue by gratefulfrog** [jdf/Processing.py-Bugs#164]
Hi,

I don't know if this is a bug, but I cannot seem to `import serial` even though it is installed in both python2.7 and 3 on my system:

```
import serial

def setup():
    None
```

results in:   `processing.app.SketchException: ImportError: No module named serial`

Yet, at the Linux command line all is fine in both python2.7 and 3

```
$ python2.7
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial
>>> 
$ python3
Python 3.5.1 (default, Apr 10 2016, 14:34:46) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial
>>> 
```

Any help would be greatly appreciated.µ
Ciao,
Bob

**Comment by jdf** [comment]
Python Mode doesn't use cPython, or your system's Python standard library.

**Comment by gratefulfrog** [comment]
Sorry for my ignorance, but is there any way to use the serial library, or
other standard libraries?

On Thu, May 26, 2016 at 7:09 PM, Jonathan Feinberg <notifications@github.com

**Comment by jdf** [comment]
Anything that's pure python can be copied into your sketch folder. There's no facility for a shared or standard Python language library for Python Mode, unfortunately.

**Comment by gratefulfrog** [comment]
So, I guess you mean that there is no easy way to use pyserial? (
https://pypi.python.org/pypi/pyserial)  Or any of the other more complex
modules?

Thanks for your help!
Ciao,
Bob
ps. I am still unable to get python mode to work properly with the 3.1
releases of processing, sigh...

On Thu, May 26, 2016 at 7:59 PM, Jonathan Feinberg <notifications@github.com

**Comment by jdf** [comment]
There is no way to use any Python module that has a C language component.

**Comment by gratefulfrog** [comment]
thanks again, sorry to be so ignorant...
Ciao,
Bob

On Thu, May 26, 2016 at 9:20 PM, Jonathan Feinberg <notifications@github.com

**Comment by gratefulfrog** [comment]
Hi,

Well after some research in this forum and on the micropython forum, I was
able to get pyserial to work with Processing.py!

Check out the details in this post:
http://forum.micropython.org/viewtopic.php?f=2&t=1840&p=11101#p11101

Thanks for all your help!!!

Ciao,
Bob
