### ISSUE TITLE
loadImage does not work from outside draw() and setup()

### ISSUE THREAD

**Issue by yzaki** [jdf/Processing.py-Bugs#165]
With the new updated version the loadImage function gives an null pointer exception if you try to use it outside the draw() and the setup() function. It used to work before from the outside as well.
This is really important to fix as you can not load images within every frame within the draw() function and if one do it inside the setup() function then its only going to be a local variable unless you declare it as global (which might not be the that good looking).

**Comment by jdf** [comment]
Yep, it's annoying, but it's working as intended. The only way to do it is

```python
def setup():
    size(300, 300)
    global bgImg
    bgImg = loadImage("banana.jpeg")
```

or, if you depend on knowing the size of your image before sizing your sketch:

```python
def settings():
    global bgImg
    bgImg = loadImage("banana.jpeg")
    size(bgImg.width, bgImg.height)
```

**Comment by BabluKumar17** [comment]
But what about if you have several jpeg or png images then how are you going to do this?

In my application, I have several images but it is unable to load those images from the file and producing errors. Any comment/help?

**Comment by jdf** [comment]
You might try the Processing Python forum for help.

https://forum.processing.org/two/categories/python
