### ISSUE TITLE
The `size()` function doesn't appear to work when called with a variable

### ISSUE THREAD

**Issue by mojones** [jdf/Processing.py-Bugs#168]
This works to resize the output window:

> size(1000,1000)

but this doesn't

> foo = 1000
> size(foo, foo)

Is this intended behaviour? On Processing 3.0.2, pyprocessing 3005.

**Comment by jdf** [comment]
Using variables for the parameters of the `size()` function requires the [`settings()`](https://processing.org/reference/settings_.html) function.
