### ISSUE TITLE
Bug in Processing 3.2.1 Python Mode 

### ISSUE THREAD

**Issue by adamako46** [jdf/Processing.py-Bugs#172]
When I use java mode the run window appears fine and everything, but when I switch to python mode, no run window appears. I can't run my python programs! I'm on a MacBook Air with OSX 10.11.5 El Capitan. Please help!

**Comment by jdf** [comment]
Are you sure it's not popping up behind the code window?

**Comment by adamako46** [comment]
It is not

**Comment by jdf** [comment]
Please paste a complete example program that doesn't work, and any error messages you might see in the console.

**Comment by adamako46** [comment]
Well, even with nothing coded, it doesn't create the window. I also tried a simple, eclipse(10, 10, 10, 10), but once again the window did not appear. In the java mode, the window appeared both with no code and with, eclipse(10, 10, 10, 10);.

**Comment by adamako46** [comment]
Also no console errors came up.

**Comment by adamako46** [comment]
Heres a video showing it not working with python and working with java.[http://sendvid.com/v1ow7nyn#](url)

**Comment by jdf** [comment]
I wonder whether you have some firewall in place? Python mode uses networking code to launch and manage the sketch runner.

**Comment by modellstadt** [comment]
Same problem here, in some situations window does not show up. Also running Mac, 10.11.
Is there already a fix/workaround?

**Comment by modellstadt** [comment]
It seems, once the problem occurs, even older scripts which were running already do not run anymore

**Comment by pshse7en** [comment]
Same problem with running windows 10. I tried a lot but it still not working in python mode.

**Comment by adamako46** [comment]
Yep I think that was it, or something like it. When I turned off my wifi, it started working again. Thanks for your help!

**Comment by jdf** [comment]
Let me make sure I understand: with your WiFi enabled, Python Mode does not work, but with WiFi disabled, it does work?

If that's so, does it stop working again when you turn WiFi back on?
