### ISSUE TITLE
Changing the value of a variable makes processing think the variable hasn't been defined

### ISSUE THREAD

**Issue by Renttooaaser** [jdf/Processing.py-Bugs#175]
It seems like if I change a variable after it's been used, procesing thinks it hasn't been defined.
As an example if I try to run:

x = 0
def setup():
    size(700,400)
def draw():
    background(255)
    ellipse(x,200,100,100)
    x += 1

it highlights the ellipse(x,200,100,100) line and prints on the console:
 processing.app.SketchException: UnboundLocalError: local variable 'x' referenced before assignment
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:248)
	at jycessing.mode.run.SketchRunner.access$4(SketchRunner.java:227)
	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:122)
	at java.lang.Thread.run(Thread.java:745)
If the x += 1 line is removed it runs, although being a static image of a circle on the edge of the screen instead of a circle going across it.

PS. It also doesn't work with x = x + 1
PS2. Doing the same thing would work in Java
PS3. I won't make that joke

**Comment by jdf** [comment]
When you're in a function, and you want to change the value of a variable declared outside that function, you have to use the `global` keyword.

```python
x = 0

def do_something():
    global x
    x += 1
```

**Comment by jdf** [comment]
(That's the way Python works; it's not related to Processing.)

**Comment by Renttooaaser** [comment]
Sorry for the inconvenience, I wasn't paying attention to the fact that I'm defining a function
