### ISSUE TITLE
Extrusion example under Image section not working :Nonetype object has no attribute loadPixels

### ISSUE THREAD

**Issue by avisrivastava254084** [jdf/Processing.py-Bugs#176]

**Comment by avisrivastava254084** [comment]
Issue resolved in the following link:
https://github.com/avisrivastava254084/py.processing/

**Comment by jdf** [comment]
Are you going to do a pull request?

**Comment by avisrivastava254084** [comment]
Yes sir I am.
Give me some time, 15-16 hours.
I am travelling and cannot use laptop, it's dead(no battery).
Please wait till then for you to verify my code.
Thanks.

**Comment by avisrivastava254084** [comment]
@jdf 
Sir, I am done with the pull request.
Thanks for consideration.
