### ISSUE TITLE
sketch crashing when drawing box()

### ISSUE THREAD

**Issue by emanoelbarreiros** [jdf/Processing.py-Bugs#185]
When running a sketch that uses the function box() the windows opens, but crashes only a few seconds later. Both versions of box have the same effect. No error message is displayed.

I am running Processing 3.2.4, Python mode build 3022, on a MacOS X 10.10.4.

Example code:
```python
def setup():
    size(300,300, P3D)
    
def draw():
    box(30, 30, 30)
```

**Comment by jdf** [comment]
The current version of Processing is 3.3.3. Please update to that version, and reopen this bug if id reproduces for you.
