### ISSUE TITLE
loadStrings returns None in Processing 3.3.6 on Windows 10

### ISSUE THREAD

**Issue by awmartin** [jdf/Processing.py-Bugs#193]
A new sketch with the following contents:

```
content = loadStrings("hello.txt")
print content
```

Prints the value None when executed. This behavior is the same whether the relevant code is placed in `setup()` or in the root level of an empty sketch. The "hello.txt" file is present in the data/ folder of the sketch folder.

![loadstrings bug in python mode 3 3 6](https://user-images.githubusercontent.com/57281/30250833-2e9a7722-960a-11e7-8508-ab5fdb6af47f.PNG)

This is the case in both the 64-bit and 32-bit versions of Processing for Windows 3.3.6.

**Comment by awmartin** [comment]
I should also add that the Python `open()` command also fails, but with file not found, where it succeeds on macOS. I've also tried with "data\\hello.txt" and the full path: "C:\\Users\\awmartin\\Documents\\Processing\\pytest\\data\\hello.txt"

![open bug in python mode 3 3 6](https://user-images.githubusercontent.com/57281/30250895-2f9a8904-960b-11e7-983e-4cc1044495b5.PNG)

**Comment by villares** [comment]
I can confirm loadStrings() is OK on Mac OS, so can anyone else test on Windows, please?

![screen shot 2017-10-09 at 10 11 22 pm](https://user-images.githubusercontent.com/3694604/31365002-f80fb374-ad3e-11e7-9139-8fcf0b81e67c.png)

**Comment by jdf** [comment]
I've tested it on Windows 10 and cannot reproduce the bug.

**Comment by awmartin** [comment]
I filed a [parallel issue on the processing.py repo](https://github.com/jdf/processing.py/issues/274). I produced it on two Windows machines but not on a third I tested. I'm assuming it has to do with something specific to those machines though, until I find a more consistent repro. Closing this one and keeping the other open.
