### ISSUE TITLE
def draw no loop with random

### ISSUE THREAD

**Issue by unoudos** [jdf/Processing.py-Bugs#194]
import random as ra
x = 0
y = 0
salto = 10
def setup():
    size(400,400)
    background(0)
    stroke(255)

def draw():
     if  ra.randint(0, 1) <= .5:
        line(x, y, x + salto, y + salto)
     else:
        line(x, y + salto, x + salto, y)
x = x + salto
#print "hola" 
#print frameCount
don't loop

**Comment by villares** [comment]
Hi @unoudos,

I have added some indentation and a `global x` statement. I seems to work fine for me.

![screen shot 2017-09-30 at 8 07 35 pm](https://user-images.githubusercontent.com/3694604/31050242-324cd52e-a61b-11e7-9673-18dc82c630d5.png)

**Comment by unoudos** [comment]
correct global x work good thanx
 but don't use framerate(5) slows down the screen printing
