### ISSUE TITLE
Python Mode does not show up on new installs in Contributions Manager

### ISSUE THREAD

**Issue by anjchang** [jdf/Processing.py-Bugs#197]
I just taught a class today where I encouraged 20 students, running both Windows and MacOS to download Processing. To my horror, the Python Mode did not show up in their contributions manager, for most of the students in the whole class.  When they brought up the contributions manager, there was no Python Mode option. They tried downloading a previous version (3.3.5) and still nothing.

One Wndows student used brew to install, and he was able to find and install Python Mode. But he also had downloaded Processing mode a few weeks ago, so not sure if his was a fresh install.

I ended up zipping my own PythonMode files and copying them into each student's modes directory. For MacOS, this was under each student's Documents/modes/ and the Windows students figured out something similar to do on their machines that worked. I couldn't reproduce it on my machine, but I could definitely see Python Mode was missing on all these "fresh" installs.

**Comment by jdf** [comment]
Augh! There was a permissions problem on the distribution. I've fixed it, and hope that the mode will reappear in the contributions manager either now or after the next processing update manager refresh, whenever that is. So sorry, and thanks for the report!

**Comment by anjchang** [comment]
Thanks, I notice you're in Cambridge... would you have time for a coffee sometime near Kendall?

**Comment by rdwrome** [comment]
just ran into this exact problem, yesterday! and used the same solution. seems like there is a permissions problem on the distribution released sometime between last thursday and yesterday (because I didn't have this problem last thursday). thank you!

**Comment by villares** [comment]
@rdwrome unfortunately Python mode is no longer maintained. Consider looking up py5coding.org as an alternative.

**Comment by rdwrome** [comment]
good to know - thanks!
