### ISSUE TITLE
MyrtoTheo -win10 64bit greek - don't see at all python mode- what do I do?

### ISSUE THREAD

**Issue by MyrtoTheo** [jdf/Processing.py-Bugs#200]

**Comment by jdf** [comment]
I'm sorry for the trouble. It should appear in the contributions manager again soon. Until it does, you should be able to download http://py.processing.org/3/PythonMode.zip and unzip it into the "modes" directory of your Processing "sketchbook" folder (which is different for each platform).

**Comment by MyrtoTheo** [comment]
Thank you!
