### ISSUE TITLE
Can't install on Mac under Java 9

### ISSUE THREAD

**Issue by jproy** [jdf/Processing.py-Bugs#207]
Having errors with introspection when trying to compile a simple demo program on MacOS Sierra.
Is it necessary to have Java 8 installed ? Specific release ?
Thanks.

**Comment by jproy** [comment]
~/Desktop/processing.py-3017-macosx$ java -jar processing-py.jar essai_pyprocessing.py 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PySystemState (file:/Users/roy/Desktop/processing.py-3017-macosx/processing-py.jar) to method java.io.Console.encoding()
WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.NoClassDefFoundError: com/apple/eawt/QuitHandler

**Comment by jdf** [comment]
Because command-line use of Python Mode is no longer officially supported, the best thing to do is to run with `--illegal-access=warn` as suggested.

**Comment by jproy** [comment]
--illegal-access=warn has no effect. Same error.
Launching processing-py.app on a demo file gives the error 
Error: Unable to access jarfile /private/var/folders/c9/4v8y64sj47bbh9790lqx317c0000gr/T/AppTranslocation/873D1802-913E-43FA-9BE1-6A0AA5544BA8/d/processing-py.app/Contents/Resources/../../..//processing-py.jar

**Comment by jdf** [comment]
Wait, what is processing-py.app?

**Comment by jproy** [comment]
I got that app together with examples etc but I don't remember where, just four days ago. What is the OFFICIAL site for py-processing ? There is one on Github, another on Google...

**Comment by jproy** [comment]
What about Java 9 ? Should I have JDK 8 or 9 will be fine ?

**Comment by jproy** [comment]
Also, is Python 3 supported ?

**Comment by villares** [comment]
Mind the way you are asking about the docs...
http://py.processing.org
Download it from processing.org + mode install from IDE
Jython based, so no Python 3 support

**Comment by villares** [comment]
It uses its own Java, no need to install any.

**Comment by jproy** [comment]
Ok, fine, I was completely lost by obsolete sites with old versions of py-processing.
Nice Job. Thanks a lot.
