### ISSUE TITLE
Issue with the run button on Mac OS X 10.10.5

### ISSUE THREAD

**Issue by torinel** [jdf/Processing.py-Bugs#209]
I'm using 3.3.6 Processing with Python on Mac OS X Yosemite 10.10.5. When I click the run button, nothing happens. There's no error message or any indication of what's going wrong. I had someone else try to use Processing on my laptop but they had the same problem. I uninstalled and reinstalled Processing but I ran into the same problem. 
<img width="704" alt="processingissue" src="https://user-images.githubusercontent.com/35472419/34966034-52e9dba4-fa1e-11e7-849f-d5cf42cf5577.png">

**Comment by villares** [comment]
Does your OS username have non-ASCII characters? (Known issue)
Is your wi-fi on? I had problems with some network proxies...

**Comment by torinel** [comment]
Hey, thanks for responding! I checked my OS username and there's no non-ASCII characters so I don't think that's the issue. I turned off my wifi and restarted, but still got nothing.

**Comment by villares** [comment]
You mean no non-ASCII I suppose (no àéñ or non-Roman?)
Just to confirm, Java mode runs fine?
Sorry I couldn't help much.

**Comment by torinel** [comment]
Whoops! Yeah, I meant no non-ASCII. Just checked and Java mode runs fine — any reason why that might be?

**Comment by villares** [comment]
No, sorry. I was just trying to eliminate the issues I know about.

**Comment by jdf** [comment]
As far as I know, the issue with non-ASCII characters is a Windows-only problem. What you're describing is more likely an issue with a network firewall or blocker.

**Comment by torinel** [comment]
Is there any way to get around the network firewall?

**Comment by jdf** [comment]
I couldn't say. If you are using a firewall, disable it and try Python Mode. If Python Mode does work, then you know it's the firewall, and can look for workarounds. If not, then that wasn't the problem.

**Comment by torinel** [comment]
My firewall was already disabled, but I enabled it and then disabled it again. Reloaded Python and things seem to work now. Thanks for your help!

**Comment by jdf** [comment]
Hmm.
