### ISSUE TITLE
Why doesn't the command "import" work anymore???

### ISSUE THREAD

**Issue by kalebkim** [jdf/Processing.py-Bugs#211]
Hi, how do you even import in processing 3.3.6? I can't import a tab because I don't even know what a module even is. Please help me!!! My sketches are ruined from imports!!

**Comment by jdf** [comment]
If you create a separate tab called `foo.py` containing
```python
def some_function(a):
    return a + 10
```

then in your main sketch tab you can say

```python
import foo

print(foo.some_function(12))
```
