### ISSUE TITLE
Undo corrupts sketch Processing 3.3.6 

### ISSUE THREAD

**Issue by rofoto** [jdf/Processing.py-Bugs#216]
I have been having an issue with undos on sketches with multiple tabs. 

After running a sketch, changing tabs and clicking undo from the menu or using the keyboard shortcut, the sketch tab I have open will scramble the text at the point where the undo would happen. 

example
tab 1 has 10 lines of code 
tab 2 has 8 lines of code 

changing line 3 of tab 2, running the sketch , clicking on tab 1 and undoing will corrupt tab 1 line 3 , instead of switching tabs to the tab 2 and undoing the change of its' line 3.

This doesn't happen every time but after a few hours of working on a sketch its scary to have something like this happen.

**Comment by jdf** [comment]
Have you verified that this doesn't affect Java mode, i.e., that it's a Python Mode bug specifically? Python Mode uses, I believe, the same editor machinery used by Java mode, though I may be mistaken.

**Comment by rofoto** [comment]
@jdf Apologies for the delay, I only saw this bug in java mode. Have not yet tried it in python mode.

**Comment by jdf** [comment]
This bug tracker is for issues related to Python Mode only.
