### ISSUE TITLE
unicodeDecodeError: 'utf-' codec can't decode bytes in position 6-8: invalid data

### ISSUE THREAD

**Issue by raimanta** [jdf/Processing.py-Bugs#221]
unicodeDecodeError: 'utf-' codec can't decode bytes in position 6-8: invalid data

I have at present a problem with processing.  Processing works normally when I open a new file. But when I record him and when I throw him, it shows me an error from the setup (). Similar for files already recorded previously. I uninstalled him of my computer and to reinstall but it changes nothing ... You can help me if it is possible. Thank you

**Comment by jdf** [comment]
Could you please paste here and example of a program that shows the behavior you describe?

What operating system?

**Comment by raimanta** [comment]
![image](https://user-images.githubusercontent.com/37912204/38171055-e5028852-3591-11e8-8c9b-f65c6e6cb0e4.png)
![image](https://user-images.githubusercontent.com/37912204/38171082-82cf2e28-3592-11e8-998e-0ddbe53e568e.png)

It's just the beginning of the program. You want it completely?
I've got Windows 10
Sorry for my english, I'm french :)

**Comment by jdf** [comment]
Can you tell me anything about your locale and language settings?

**Comment by villares** [comment]
Could you also please tell us the path to your sketchbook folder (something like C:/.../Processing/)?
