### ISSUE TITLE
Can't use video library in PythonMode

### ISSUE THREAD

**Issue by newton45** [jdf/Processing.py-Bugs#229]
Processing can't run this code below:

```
add_library('video')

def setup():
    size(640, 360)
    background(0)
    
    movie = Movie(this, "transit.mov")
    movie.loop()
    
def movieEvent(m):
    m.read()
    
def draw():
    image(movie, 0,0,width,height)
```

Error says "processing.app.SketchException: java.lang.RuntimeException: Could not load movie file transit.mov"

**Comment by jdf** [comment]
Have you added `transit.mov` to the sketch's data folder?

**Comment by villares** [comment]
Hi, @newton45,

I can confirm *it works for me* after adding `global movie` inside `setup()` (and having a `transit.mov` file in the `data` folder, as you can see on the screen shot.

![screen shot 2018-06-02 at 10 04 50 pm](https://user-images.githubusercontent.com/3694604/40882222-87b3baf8-66b1-11e8-821d-a70e4d855eec.png)
