### ISSUE TITLE
Can't install pythonmode

### ISSUE THREAD

**Issue by photoelectron** [jdf/Processing.py-Bugs#234]
I've looked at previous posts about a similar issue but haven't found a solution.

Today, I opened processing after a couple of months of not having done so. My pythonmode version was around 3 versions older than the latest one (3040), so I clicked on update. I got a message saying it couldn't do a backup and then it asked to restart. I restarted processing and then pythonmode was gone, so I went to install it again but not I get a message that says "could not find a mode in the downloaded file". I've noticed that processing downloads a 1 kb corrupted .zip file to a temp folder in Windows 7 x64 and that it doesn't delete it after closing. 

I also tried manually installing (by downloading from a link to the .zip posted on another similar issue), but Processing doesn't recognize the pythonmode in the modes folder. Sometimes, after going to the modes window in processing and then exiting it, I'll get a message in the console saying something about this version of python mode is not compatible, or something similar (this doesn't always show up and I haven't grabbed a screenshot)

**Comment by villares** [comment]
Hi Arsénico, sorry to hear your struggle.
Could you check your Processing IDE version? May I suggest a fresh IDE
install?

**Comment by photoelectron** [comment]
Hi,
When the problem started, I already had 3.3.7, but I still downloaded it again in case some file had been lost or corrupted. I also deleted the files in the %appdata% Processing folder (where the preferences file is), so that the program would generate them again, but the problem remained.

**Comment by villares** [comment]
Have you tried downloading from https://py.processing.org/3/PythonMode.zip ?

It seems related to this issue: https://github.com/processing/processing/issues/5554

**Comment by photoelectron** [comment]
Yes, I downloaded that zip and placed it in the modes folder and that's where I would occasionally get the message about the version not being compatible with the version of processing.

I looked at that issue but I couldn't find anything that helps.

**Comment by raj-raghuwanshi** [comment]
@photoelectron Yeah, it is not working for me either. Even when I placed it into the modes folder in the java folder, it still said "Could not find a mode in the downloaded file", and I never got the other error you got. (I'm using the Mac OS)

Edit: It worked! @villares helped me figure out what I was doing wrong.

**Comment by gripp** [comment]
Is there a resolution to this issue yet? How did you get it working? I'm having the same problem trying to install Python mode on a Mac.

**Comment by raj-raghuwanshi** [comment]
@gripp What you want to do is download the Python Mode from this file: https://py.processing.org/3/PythonMode.zip.

Then, you want to go to documents, open the Processing Folder, then from there, go to the Modes folder, and place the extracted Python folder (which is in the zip).

Basically
Documents>Processing>Modes, then drag the PythonMode folder into the Modes folder, and it should work.

**Comment by gripp** [comment]
Thanks! That totally worked!

Seems like there is still some underlying problem. Should be able to install Python mode via the GUI, obviously. But thanks for documenting the workaround.

**Comment by photoelectron** [comment]
I downloaded the PythonMode.zip again and it's working now. 

I think I was getting an older version of PythonMode.zip because the files had dates from like 2015, but I had thought it was from when they were first created. Now the files have 2018 dates.

Also, I noticed that when I clicked the link to download PythonMode.zip, the two /'s surrounding the 3 would disappear on the URL after the prompt to download the file appeared. That's not happening now.

Anyways, thanks all for the help.

**Comment by aayevtushenko** [comment]
I have the most recent version of Processing installed and still face this issue.
I downloaded the attached file and put it into the processing root folder's (the file system processing creates) modes file. So it's processing > modes > PythonMode. 
The menu still only shows Java and p5.js.
@villares do you have any idea how to make it show up in the menu?

![image](https://user-images.githubusercontent.com/33838118/71317563-229eba00-2451-11ea-868f-ce3897aed3c8.png)
![image](https://user-images.githubusercontent.com/33838118/71317568-2fbba900-2451-11ea-9135-9a1ce4a2595b.png)

**Comment by villares** [comment]
Hi @aayevtushenko !

You are putting the downloaded `PythonMode` folder inside the wrong `modes` folder!
It is not inside the `processing-3.5.3` folder, there should be a `Documents > Processing > modes`, you will find the *p5.js* mode there too!

HTH
