### ISSUE TITLE
can I embed a Processing.py sketch on web page?

### ISSUE THREAD

**Issue by ashmanskas** [jdf/Processing.py-Bugs#242]
Is there a straightforward way to embed a Processing.py sketch into a web page?  Is "Skulpt processing" the state of the art for trying to do so?  https://github.com/skulpt/skulpt/wiki/Skulpt-Processing

**Comment by jdf** [comment]
I wouldn't have any idea how to do that. Python Mode uses Processing's Java runtime.

**Comment by tildebyte** [comment]
@ashmanskas Yes, skulpt seems to be the least worst option :)
