### ISSUE TITLE
"rows" keyword highlight

### ISSUE THREAD

**Issue by pikeas** [jdf/Processing.py-Bugs#246]
"rows" is not a keyword but seems to be highlighted.

<img width="155" alt="screen shot 2018-10-03 at 00 11 21" src="https://user-images.githubusercontent.com/686573/46395366-f0186e00-c6a0-11e8-89b1-d7314aff4781.png">

Processing 3.4, Python mode 3042. `rows` is not a function nor a predefined variable, so its highlighting as a keyword appears to be incorrect.

**Comment by villares** [comment]
Can this be a side effect of the .row() method of the Table class?
https://processing.org/reference/Table_rows_.html
Maybe the syntax highlight list came from the reference items list.

**Comment by pikeas** [comment]
Same issue for `start` and `end`. Both words are undefined names but receive syntax highlighting as keywords.

Also, valid Python keywords (for example, `xrange`) are *not* highlighted.

**Comment by jdf** [comment]
Alexandre is right; it's because of Table.rows(). I'll nuke it, start, and end, and I'll add xrange.

Feel free to issue pull requests on [this file](https://github.com/jdf/processing.py/blob/master/mode/keywords.txt).
