### ISSUE TITLE
import PDF library in linux does not work

### ISSUE THREAD

**Issue by dalanicolai** [jdf/Processing.py-Bugs#247]
On linux (Fedora 28). When I try to export to pdf (see example file) in Processing 3.4 I get the following error message: 

You need to use "Import Library" to add processing.pdf.PGraphicsPDF to your sketch.

I added the pdf import statement via the Import Library in de Sketch menu as can be seen in the attached example file (that produces  the error. changed extension from pyde to txt so that github accepts it as attachmnet)

[pdfTest.txt](https://github.com/jdf/Processing.py-Bugs/files/2471598/pdfTest.txt)

**Comment by jansindl3r** [comment]
I have the same problem on Windows 7, any solution yet?

**Comment by jdf** [comment]
I have found that, as with the examples in the main Processing mode, you must declare your PDF output in `setup`. This program works for me:

```python
add_library('pdf')

def setup():
    size(400, 400, PDF, "/tmp/out.pdf")

def draw():
    ellipse(200, 200, 50, 50)
    exit()
```
