### ISSUE TITLE
LowLevelGL example not working

### ISSUE THREAD

**Issue by villares** [jdf/Processing.py-Bugs#250]
As I'm looking at each and every Processing IDE example for my dissertation, I found this one not working under Windows or Ubuntu 16 (can't test on Mac OS now because my MacBook broke down).

https://github.com/jdf/processing.py/blob/master/mode/examples/Demos/Graphics/LowLevelGL/LowLevelGL.pyde

Python Mode can't recognize `PGL` as in `PGL.FLOAT`

**Comment by jdf** [comment]
The PGL interface has changed, and they rewrote that demo. I'll port them to Python and fix the PGL Python Mode implementation.
