### ISSUE TITLE
The "Library" examples on the IDE do not reflect the files on the processing.py repo

### ISSUE THREAD

**Issue by villares** [jdf/Processing.py-Bugs#251]
Examples for the built-in libraries, like PDF and DXF export look good in the repo:
https://github.com/jdf/processing.py/tree/master/examples.py/Library

But on the Processsing IDE one still gets the Java versions when clicking at the Python Mode examples panel. 

Is it this a Processing IDE issue maybe?

**Comment by jdf** [comment]
Those examples were created for the standalone processing.py distribution, and not the mode.

**Comment by villares** [comment]
I see what you mean, but Processing IDE users could benefit a lot from them... how could we make more people find them?

**Comment by jdf** [comment]
They would have to be ported to Python Mode

**Comment by villares** [comment]
I have asked a friend to pair with me and finish porting them. I hope I can finish my dissertation before that...

**Comment by jdf** [comment]
😲What is your dissertation on?

**Comment by villares** [comment]
A taxonomy/thesaurus of themes/topics for teaching programming on a visual context
