### ISSUE TITLE
How can it use py3

### ISSUE THREAD

**Issue by lingoWu** [jdf/Processing.py-Bugs#257]
How can pyProcessing use py3, just need to use some important lib like pytorch in py3

**Comment by villares** [comment]
Hi @lingoWu !

I'm afraid this is the wrong channel for your question. Here is the place for reporting bugs/issues in the project. I suggest you close this and try searching http://discourse.processing.org

I would also like to tell you it's very hard to integrate, and possibly impossible, to use code you might want  in Python 3 with Processing.Py, as it is based on Jython that is Python 2 and unable to access C-extended libraries.
