### ISSUE TITLE
[Mac] [Processing 3.4] Python Processing not running and no error message

### ISSUE THREAD

**Issue by Wholzman** [jdf/Processing.py-Bugs#263]
Hi, I've recently re-downloaded Python Processing on my laptop and I have been having an issue where the java mode is running without error, but when I change to the python mode no sketches run but I'm not provided with any errors. I've tried everything from running projects with just the code print("Test"), to running the pre-made examples, and none work (No graphical interface shows up and no console messages). I've already checked if its a problem with my firewall or my installation of processing, however after uninstalling and reinstalling multiple times I've decided it can't be that. 

Thanks!
Will

**Comment by jdf** [comment]
Hi. What demonstrates that it's not a networking-related issue (i.e., a firewall problem)?

**Comment by Wholzman** [comment]
Thanks for the quick response. I figured it was a firewall problem at first, however when I checked my firewall it said processing was approved, and just to be certain, I disabled my firewall as well to see if it would fix the problem, but it did not.

**Comment by Klannato** [comment]
Getting a similar issue in elementary Linux funnily enough, processing refuses to run any code. No error messages or anything.

**Comment by jdf** [comment]
It's not "Processing" that's being blocked; it's "Java". Python Mode launches an entirely separate process to run sketches, and it's that process that's being blocked, I think.

**Comment by orgicus** [comment]
@Wholzman I just encountered the same issue with Processing 3.4

After upgrading to Processing 3.5.3 I can confirm the sketches simply run as expected

**Comment by jdf** [comment]
Weird. Thanks for letting us know.
