### ISSUE TITLE
Reloading saved image produces different image.

### ISSUE THREAD

**Issue by vincematsko** [jdf/Processing.py-Bugs#275]
In doing image processing, I am discretizing colors so that an image is rendered with just seven colors.  I save the window using saveFrame().  I immediately reload into a different image, and find that the colors have changed slightly - close, but no longer discretized.

Is there a way to use saveFrame() which maintains the exact RGB values of each pixel?  I thought this would be the default, but it seems that some other algorithm is used.

**Comment by villares** [comment]
Can you provide minimal code to reproduce?

What is the format you are saving the frame as? Have you tried .gif or .tga
or anything else?

**Comment by vincematsko** [comment]
Here is a screen shot - hard to reproduce with a few lines of code.  I can attach the .pyde file and image used, if necessary.  The basic issue is that on frame 1, I save an image and print RGB values of pixel 0.  On frame 2, I load the saved image and print RGB values of pixel 0, and they've changed.

![processing](https://user-images.githubusercontent.com/11161159/63216173-89a50e80-c0ff-11e9-8f2a-46cde563a315.png)

**Comment by jdf** [comment]
As @villares suggested, JPEGs are lossy, and there's little relationship between input pixel and output pixel. You'll need to use a lossless format such as PNG.

**Comment by villares** [comment]
I'm unable to examine this right now, but I'm afraid there is no problem in
Processing, the thing is you are saving in .jpg which compresses and
manipulates colours on save!
