### ISSUE TITLE
import other python libarary

### ISSUE THREAD

**Issue by DevilYang1997** [jdf/Processing.py-Bugs#289]
How to **install and import other python library** like numpy in python mode?Maybe,it is impossible in processing?

**Comment by villares** [comment]
Hi @DevilYang1997 !

Issues are made for reporting bugs or discussing reasonable features. For general questions, please use the forum at https://discourse.processing.org/c/processing-py/

As you will see this has been asked many times there. Only Java or pure Python libraries (without extensions in other languages) can be used with Processing Python mode, and *numpy* is not one of them.

Please close this issue! :)

**Comment by DevilYang1997** [comment]
> 
> 
> Hi @DevilYang1997 !
> 
> Issues are made for reporting bugs or discussing reasonable features. For general questions, please use the forum at https://discourse.processing.org/c/processing-py/
> 
> As you will see this has been asked many times there. Only Java or pure Python libraries (without extensions in other languages) can be used with Processing Python mode, and _numpy_ is not one of them.
> 
> Please close this issue! :)

Thanks a lot!
