### ISSUE TITLE
Python mode 5058 not running any sketch

### ISSUE THREAD

**Issue by villares** [jdf/Processing.py-Bugs#291]
On Ubuntu 18.04.4  and on MacOS 10.11.6  (saw a "can't run sketch service" message once)

After a Python mode update  (by means of 'remove' and then 'install' on the IDE):
- The 'Run' button flashes and nothing happens (no error message).

Reverting to my previous 5056 mode works again.

**Comment by jdf** [comment]
Sorry, folks. Build 3059 is going up now. I had built the mode with a more recent version of Java, which Processing doesn't support.
