### ISSUE TITLE
size method not does not function correctly in python mode

### ISSUE THREAD

**Issue by Alfertp** [jdf/Processing.py-Bugs#298]
Processing 3.5.4 within Win 10 environment
No matter what value is put in size method,
The result canvas would be 100pixels * 100pixels big.
Even with code as simple as:
def setup():
    size=(200,400)
![printscreen](https://user-images.githubusercontent.com/64370026/83785899-44ec6300-a692-11ea-8e6b-01f78ec253f6.png)

**Comment by villares** [comment]
Hi @Alfertp !

You made a mistake, you should call size as a function/method! `size(200, 400)`
Your code shows you creating a variable named `size` (`size = (200, 400)`) that can't work. 

Be sure to check the documentation: https://py.processing.org/reference/size.html
Please close this issue :)

**Comment by Alfertp** [comment]
> 
> 
> Hi @Alfertp !
> 
> You made a mistake, you should call size as a function/method! `size(200, 400)`
> Your code shows you creating a variable named `size` (`size = (200, 400)`) that can't work.
> 
> Be sure to check the documentation: https://py.processing.org/reference/size.html
> Please close this issue :)

oh, how silly I am. I should have checked that. Thank you very much!

**Comment by villares** [comment]
I think my first issue was a mistake too, something about `translate()` & `pushMatrix()`/`popMatrix()` and I was doing it wrong :) Don't let it discourage you, @Alfertp! 

Also, check the http://discourse.processing.org Processing.Py category for friendly support.
