### ISSUE TITLE
Update to python 3

### ISSUE THREAD

**Issue by Pomax** [jdf/Processing.py-Bugs#314]
The Python Processing mode still uses Python 2.7, which that's been EOL since January 1st 2020, and is now a security liability. Would it be possible to update it to python 3 instead (and even better, offer two versions: one that comes with python, and one that goes "we know you already have python installed, we're going to assume the executable is called `python` and if that doesn't work, please download the full version instead"?)

**Comment by jdf** [comment]
In fact, it uses Jython 2.7, not CPython at all.

**Comment by Pomax** [comment]
Hm, might be worth seeing if there is a Jython 3 that is just mature enough to warrant at least offer a "beta" mode for then, given that Python 2.7 has been EOL in its entirety, which doesn't just mean that "the interpreter/compiler" isn't supported anymore, but also that the 2.7 API is now very much dead. Python 3 changed quite a few elementary behaviours, as well as a lot of the API, so anyone who learns Python today will _not_ be learning Python 2.7, and if they first learn Python and then move on to Processing-using-the-python-flavour, they're going to have a bad time =(

Or perhaps there's a compatible alternative?
