### ISSUE TITLE
No sketch window

### ISSUE THREAD

**Issue by myPicts** [jdf/Processing.py-Bugs#336]
Hi there
I am trying processing 4 on a M1 Mac running macOS Monterey. If I am using python, there is no sketch window.
Works fine with Java. 
Is that not working (yet) or am I doing something wrong?

**Comment by villares** [comment]
Hi @myPicts! 
Yeah, it's not working yet.
Unfortunately we have to stick to Processing 3.5.4 for Python mode at this time.

**Comment by myPicts** [comment]
Thanks, Alexandre. Good to know that. Idea: write just that sentence on the https://py.processing.org-page. Have a great holiday break and New Year!
