### ISSUE TITLE
Can't install python ode in processing4.

### ISSUE THREAD

**Issue by AaryaZ** [jdf/Processing.py-Bugs#342]
![python md](https://user-images.githubusercontent.com/70696659/150679142-fa746917-9705-45d5-b473-639a2cd8cb9d.png)

It shows that the python mode is not compatible.

**Comment by tabreturn** [comment]
There is no Python Mode for Processing 4 (it is labelled "Python Mode for Processing 3"), but the developers are working on it. Use Processing 3.5.4 for Python Mode for now.

**Comment by jdf** [comment]
Hi, folks. Python Mode for Processing 4 is in testing now, and should show up in your mode installer real soon now.

**Comment by tabreturn** [comment]
Fantastic news!
