### ISSUE TITLE
Python tracebacks not reported with Processing 4.0 b8

### ISSUE THREAD

**Issue by the-fortran-programmer** [jdf/Processing.py-Bugs#354]
I have not been using processing.py before and I am running Processing 4.0 b8 under Windows 10. 
When my Python sketch entcounters a traceback error, the sketch just stops and I don't get any notification. Is that a bug, a feature or just a question of configuration?

**Comment by tabreturn** [comment]
I recommend you use Processing 3.5.4 for Python Mode. At least until Processing 4 is out of beta.

**Comment by the-fortran-programmer** [comment]
Thank you tabreturn, works fine.
