### ISSUE TITLE
can't build processing.py for processing4 from committed source, despite python mode being available for processing4

### ISSUE THREAD

**Issue by KurtSteinkraus** [jdf/Processing.py-Bugs#359]
I'd like to get python mode working for processing4, in particular, fixing https://github.com/jdf/Processing.py-Bugs/issues/347 and whatever error is causing:
```
  Hmm. Can't load native code to bring window to front using the absolute path:
  /Users/kurts/Documents/Processing/modes/PythonMode/mode/libjniosx.dylib.
  Hmm. Can't load native code to bring window to front.
```

To do that, I need to be able to build processing.py for processing4 and have it nominally work.
It seems like there's some basic processing.py support developed somewhere for processing4, since python mode is available for processing4.
But the processing.py repository still seems to work only with processing3.

I've tried making local changes to get it to work with processing4:

  - I commented out undefined references to PSurfaceFX, since they only seem related to error-handling.
  - I pointed the build and test scripts at the processing4 directory.

 I can get the project to build.
(The tests fail with what looks like an error due to java's platform module system, but the locally built python mode seems to load fine.)
I can get testmode.sh to start my locally built Processing4 with my locally built python mode.
However, when I try to run a simple python sketch, I get the error:
```
  java.lang.NullPointerException
	at jycessing.Runner.runSketchBlocking(Unknown Source)
	at jycessing.mode.run.SketchRunner.lambda$startSketch$3(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
I'd chase it down, but I thought I'd ask here first:

Where are the changes that allow processing.py mostly to work with processing4?

**Comment by jdf** [comment]
You have to switch to the processing4 branch.

Keep in mind that Python Mode is unmaintained.
