### ISSUE TITLE
in the python version, everything is 25% bigger than what must be 

### ISSUE THREAD

**Issue by Aria-AAs** [jdf/Processing.py-Bugs#360]
I noticed this size conflict and low accuracy in the python version a few months ago and made an issue for it, but after that I got sick and I was in the hospital for about one month
anyway the issue is still alive so I look at it more accurate and noticed that that size conflict has a ratio and try to find it and as you can see its 25%
I used an application called "Snagit" to see how many pixels are on the screen captured by the application.
java version with 800x800 size:
![java_800](https://user-images.githubusercontent.com/58929531/175879761-3b86ede4-cbd0-44a3-8c6a-2279e768231a.PNG)
python version with 800x800 size: (as you can see it captured 1000x1000 pixels.)
![python_800](https://user-images.githubusercontent.com/58929531/175879776-c77a60f2-7dfa-4498-bbc6-ee139961e716.PNG)
java version with 400x400 size:
![java_400](https://user-images.githubusercontent.com/58929531/175879830-95f17189-4206-471b-a55f-8f5bdd3b3113.PNG)
python version with 400x400 size: (as you can see it captured 500x500 pixels.)
![python_400](https://user-images.githubusercontent.com/58929531/175879839-cd188695-3840-4654-a0aa-17d27796b30e.PNG)
java version with 100x100 size:
![java_100](https://user-images.githubusercontent.com/58929531/175879878-dd23a04b-dad3-498c-94e7-19b55ae656f6.PNG)
python version with 100x100 size: (as you can see it captured 125x125 pixels.)
![python_100](https://user-images.githubusercontent.com/58929531/175879896-11e68e0d-4952-4c02-b0c0-f10998cbff2e.PNG)

**Comment by tabreturn** [comment]
It seems the Windows display scale settings can lead to these types of issues. But the `save()` function creates an image of the proper size regardless of the display scale: https://github.com/jdf/Processing.py-Bugs/issues/353

Also: there are issues with Processing 4 and Python Mode. Use Processing 3.5.4 for now.
