### ISSUE TITLE
Sketch window appears under other windows or not at all

### ISSUE THREAD

**Issue by esperanc** [jdf/Processing.py-Bugs#42]
(Processing 2.2.1, Processing.py build 337, Mac OSX Mavericks)

These possibly are two separate issues, but I think they are related.

Issue 1: Whenever a sketch is run, the graphics window  appears under other windows. In particular, it appears at a lower stacking level than the PDE window that started the sketch. If there is room in the desktop so that the window fits to the left of the PDE window, this is not a serious issue, but if the graphics windows is somewhat large, the lower stacking order will make the PDE window actually cover the graphics window, so that the only way to see it is to move the PDE window out of the way. Moreover, the graphics window does not receive the mouse focus by default. Even worse, it is not recognized by the Finder / OS either as a separate application (e.g. as a Java application in the case of Java Processing) or as part of the Processing application. This means that we cannot put the sketch application in foreground using the usual means for Mac OS, such as  cycling  amongst the Processing windows using Cmd-` or cycling through applications using Cmd-TAB. To reproduce this behavior, just run an empty sketch with the PDE window placed close to the left edge of the desktop.

Issue 2: The graphics window may never appear at all. I've had this problem on several occasions. One sure way to trigger this behavior is as follows: (a) Start the PDE and create an empty sketch in Python mode. Run it and the graphics window appears after a while. (b) Create a new sketch in Java mode, but do not close the Python sketch.  Run the empty Java sketch and the little 100x100 graphics window appears as expected. (c) Now go back to the Python sketch and run it. Although the "Play" button stays highlighted, no graphics window appears. Because of issue 1, it may have been mapped to some invalid desktop position and we will never know, since there is no way to put it in foreground.

**Comment by falquaddoomi** [comment]
I'm still having issue 1 on OS X Mavericks 10.11.6, specifically that the running sketch appears behind the editor. I'm on "Build 3022, built 2017/04/17 17:25" according to the "Modes" screen in Processing's contribution manager. I'm on Processing 3.3.4, freshly installed earlier today.

**Comment by jdf** [comment]
There's nothing I can do about it, as far as I know.

**Comment by falquaddoomi** [comment]
No problem, just wanted you to know that it's still an open issue, or at least an unfixable closed one and not a fixed closed one, as you'd be lead to believe if you came across this issue thread when searching.
