### ISSUE TITLE
PDEX/Tweak Mode features

### ISSUE THREAD

**Issue by kazimuth** [jdf/Processing.py-Bugs#88]
The new Java Mode in Processing 3 (was PDE-X/Tweak Mode for a while) has some very nifty features it would be cool to emulate:
-Autocompletion
-Syntax error detection
-Code modification at runtime
-Breakpoints and variable inspection
Some of these are much harder in Python, but some of them are easier - I think it might be possible to actually modify the various sketch-methods at runtime, rather than only tweaking constants.
This might add significant complexity to the implementation, but I think it would be worth it.
This is very low priority - we're not feature-complete yet - but I'd like to at least put it on the radar and see what people think.

**Comment by ozel** [comment]
I am curious if anyone is still working on the Tweak Mode and new ways of interaction. 
How difficult would it be to render the canvas in a javascript compatible way? 
I am thinking here to integrate processing's python kernel into a jupyter.org notebook! (check also the recent jupyterLab alpha release to get an idea of the full potential of this quickly rising platform)
How much is the current python mode API tied to the java code of the Processing IDE?

**Comment by jdf** [comment]
Python mode depends entirely on Processing's Java infrastructure. It is a PApplet that exposes processing functions to a Jython interpreter.
